CREATE DATABASE java_comment_api;
USE java_comment_api;
CREATE TABLE comment (
  id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  domain VARCHAR(100) NOT NULL,
  path VARCHAR(100) NOT NULL,
  content VARCHAR(5000) NOT NULL,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
);